export enum ChatRoomsWSEvents {
  JOIN_ROOM = 'JOIN_ROOM',
  CHAT_TO_SERVER = 'CHAT_TO_SERVER',
  CHAT_TO_CLIENT = 'CHAT_TO_CLIENT',
  LEAVE_ROOM = 'LEAVE_ROOM',
  REFRESH = 'REFRESH',
  LEFT_ROOM = 'LEFT_ROOM',
}
